services:
  - type: web
    name: weather-app-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false

  - type: web
    name: weather-app-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_ENV
        value: production
